spring:
  main:
    banner-mode: "off"
  profiles:
    active: production
  datasource:
    url: jdbc:oracle:thin:@DB_SERVICE_high?TNS_ADMIN=/PATH/TO/WALLET
    username: ADMIN
    password: "DB_PASSWORD"
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-classname: oracle.jdbc.pool.OracleDataSource
      sql-for-validate-connection: select * from dual
      connection-pool-name: connectionPoolName1
      initial-pool-size: 5
      min-pool-size: 5
      max-pool-size: 10
    jpa:
      hibernate:
        use-new-id-generator-mappings: false
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
oraclecloud:
  region-name: "REGION"